title = "MakeDevGo"
baseURL = "http://makedevgo.com/"
tags = ["portfolio", "web design", "blog", "Go", "gamedev","programmer"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Make. Develop. Go."
    author = "Daniël Pels"
    description = "Developer, Gamedev and Golang enthusiast based in Amsterdam."
    logoBig = "/images/danielPortfolioLogo.svg"
    logoSmall = "/images/danielPortfolioLogo.svg"
    favicon = "favicon.ico"
    opengraphImage = "/images/danielPortfolioLogo.svg"
    twitter = "Fissersboot"
    linkedin = "daniel-pels-12364883"
    github = "DanielPels"
    facebook = ""
    email = "daniel@makedevgo.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
